### ISSUE TITLE
How can I display 3D model on IPhone?

### ISSUE THREAD

**Issue by dream811** [epam/mriviewer#13]
Dear Vladislav Shubnikov!
I am here again,
I can't display 3D model on iphone safari@google chrome
Is it impossible problem?
Thanks again !

**Comment by VladislavShubnikov** [comment]
Hello again,
Unfortunately current version is not working with mobile browsers. In our next grand update we hope to support SOME (not all) android-based mobile devices (with limitation to fast enough video card) and mobile browsers. It will happened in 1-2 monthes later.

**Comment by svoboda-rabstvo** [comment]
@VladislavShubnikov can it related with error on Opera (v. 62.0.3331.99) and Chrome (v. 75.0.3770.)? I'm about demo env. (https://med3web.opensource.epam.com/)

![image](https://user-images.githubusercontent.com/10900467/62575015-72b22100-b8a2-11e9-8fbb-599a11417f0b.png)

**Comment by DanilRostov** [comment]
@dream811 thank you for opening this issue.

We are still working on the mobile support and soon it will be ready.
