### ISSUE TITLE
Cant install or run

### ISSUE THREAD

**Issue by AdolfoBanchio** [epam/mriviewer#133]
When i try to run `npm install` or `npm run start` I get a bunch of errors and warings. Similar to this case https://github.com/epam/mriviewer/issues/126

Also in the demo aviable in this repo I cant load a .dcm file

**Comment by DanilRostov** [comment]
@AdolfoBanchio Thanks for opening an issue.

We have released version 2.0 of MRI viewer. Could you try to reproduce please?
If you face any problems please open new issue with details.
Thank you

**Comment by vesper8** [comment]
For me I just had to use node 16, using nvm, to get it to work. On 18 and 20 it does not work, including the new 2.0 release. I think it should be made clear in the readme that this requires node 16.
