### ISSUE TITLE
I have strange error.

### ISSUE THREAD

**Issue by dream811** [epam/mriviewer#16]
If run this app on several browser (or duplicated url on a browser) and when several clients connect  this app's url at a time, other clinet's action click will be display in another's browser.
![Screenshot from 2019-04-17 02-06-09](https://user-images.githubusercontent.com/45660446/56264736-687ed380-60b5-11e9-9b8b-e5cc4656a0b4.png)

**Comment by DanilRostov** [comment]
@dream811 thank you for opening this issue.

Recently we have released MRI-viewer version 2.0. You could try it out.
If you face any problems please open new issue with details and screenshots.
Thank you.
