### ISSUE TITLE
Is it possible to open DICOMDIR

### ISSUE THREAD

**Issue by ffflabs** [epam/mriviewer#19]
My EMR images are stored, as exported by a PACS server, with the following structure:

![image](https://user-images.githubusercontent.com/238439/61884979-17a82380-aecb-11e9-96bb-f3fde20b2c02.png)

If I drag the DICOMDIR file into [DicomParser's example](https://rawgit.com/cornerstonejs/dicomParser/master/examples/dragAndDropDump/index.html) I see it's correctly decoded:

![image](https://user-images.githubusercontent.com/238439/61885119-4c1bdf80-aecb-11e9-9aca-e0da81a4a8a7.png)

So I must be missing a step here. Am I supposed to encapsulate the whole contents of the `emr_files` folder into a `ktx` file?

**Comment by DanilRostov** [comment]
Dear @ffflabs , recently we released this feature. You could try it out and open new issue in case you have something else. Thank you
