### ISSUE TITLE
Build issues with Node 12 LTS

### ISSUE THREAD

**Issue by knopkem** [epam/mriviewer#22]
Latest LTS and gulp3 don't play well together. 

```
[18:18:32] Requiring external module babel-register
fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
```

I forked and 'fixed' this via: https://stackoverflow.com/a/58394828 but it's not a solution. You should update to gulp4

**Comment by VladislavShubnikov** [comment]
Hope, we have fixed gulp 3/4 compatibility problem. Now gulp4 is required in package.json.

**Comment by Phreak87** [comment]
create a file "npm-shrinkwrap.json" and paste this content:

    {
      "dependencies": {
        "graceful-fs": {
            "version": "4.2.2"
         }
      }
    }

then run 'npm-install' and gulp again.
worked for me.

**Comment by DanilRostov** [comment]
Migrated to Node 16
