### ISSUE TITLE
Demo live example doesn't work

### ISSUE THREAD

**Issue by laurennlam** [epam/mriviewer#26]
I tried to open the web page which shows the demo live.
But it doesn't work.

**Comment by alterfo** [comment]
@laurennlam hello!
Can you please try to open it via Google Chrome browser?

**Comment by DanilRostov** [comment]
@laurennlam thank you for opening this issue,

Recently we have released MRI-viewer version 2.0. You could try it out.
If you face any problems please open new issue with details and screenshots.
Thank you.
