### ISSUE TITLE
UI is not modern

### ISSUE THREAD

**Issue by alterfo** [epam/mriviewer#41]
Please see Jira.

**Comment by alterfo** [comment]
During the investigation I hit a problem with modals - they are not exist in design concept. 

@Dmitrii-Romanov, can we use [IBM's Carbon Design System](https://www.carbondesignsystem.com/) instead of current [react-bootstrap]()
Argumentation:
- Carbon Design System is React-first, but Bootstrap is not;
- Bootstrap-react is not customizable and app looks like a prototype.

@DanilRostov any comments, objections, suggestions?

**Comment by DanilRostov** [comment]
> During the investigation I hit a problem with modals - they are not exist in design concept.
> 
> @Dmitrii-Romanov, can we use [IBM's Carbon Design System](https://www.carbondesignsystem.com/) instead of current react-bootstrap?
> 
> Argumentation:
> 
> * Carbon Design System is React-first, but Bootstrap is not;
> * Bootstrap-react is not customizable and app looks like a prototype;
> * Bootstrap doesn't fit new design concept, so we will get rid of it
> 
> @DanilRostov any comments, objections, suggestions?

No objections from my side, and I think we need to discuss it with design team.

**Comment by Dmitrii-Romanov** [comment]
We are talking about https://github.com/carbon-design-system/carbon which is under Apache License Version 2.0. If so, I don't see any obstacles to use it.

**Comment by alterfo** [comment]
Carbon appears to be too complex for our app, lets consider https://onsen.io/ for a "far prototype" version.

**Comment by abitrolly** [comment]
@alterfo can you post some screenshots what you want to remove? If a software if already functional, playing with design is not always a good move, as their existing workflow may break.
