### ISSUE TITLE
how to pass a URL to index.html

### ISSUE THREAD

**Issue by djsg** [epam/mriviewer#7]
I want to call med3web page (index.html) from another webpage with a URL link; so when med3web page is onloaded, it is automatically going to load dicom files pointed by URL.
How to achieve that?

**Comment by djsg** [comment]
In the built main.js file, I modified init function at line 125xx to the following:

        key: "init",
        value: function() {
            if ((new c.default).checkValidBrowser() || console.log("Found non valid browser"), this._initScene2d(), !this._initScene3d()) return !1;
            var t = !0;
                        
            this.m_options.loadUrlFile = "http://serverip/3d_dicom/data/files_1";
                        
             return this.m_options && this.m_options.loadUrlFile 
                    && this.m_options.loadUrlFile.length > 1 ? 
                    (t = this.loadScene(this.m_options.loadUrlFile, this.m_options.loadType)) 
                     || (0, o.default)({
                     title: "Error load",
                     text: "Cant read scene",
                     icon: "error",
                     button: "continue"
             }) : console.log("Med3Web.init without load scene"), this._run(), t

It didn't work; the URL is not passed to loading function.

**Comment by VladislavShubnikov** [comment]
There are 2 ways to load some volume on application startup:
1) Load volume, placed in local application folder structure
2) Load volume, referenced by URL from some remote location in Web.

You need to write reference to loaded on stratup file in project/tools/config.js.
Both ways with more details:

1) You can place some file in ProjectFolder/app./data folder. For example, 'lungs.ktx' is already placed here to illustrate loading posibilities. In this case you need to setup config.data.onloadsrc: 'data/lungs.ktx',
Implementing this way, you can place some not-very-large files directly inside web app build and this file will be acessed locally by application. Pros: loading can be quick. Cons: Application build will contains this file inside.

2) You can place some files (single *.ktx file or folder with a lot of *dcm files) somewhere on your web site and Med3Web application will load this file(s) from specified URL on startup stage.
If you need to load KTX file on startup, please put your somevolume.ktx file to your location and specify URL like:
config.data.onloadsrc: 'http://yoursite.com/folder1/folder2/somevolume.ktx'

If you need to load folder with *.dcm files, you need to put all your dcm files in seperate folder (containing only these dcm files) and create special file 'file_list.txt' with just list of all files. You can create file_list.txt by running command:
dir *.dcm /w /b > file_list.txt
After that yo need to specify URL in tools/config.js like:
config.data.onloadsrc: 'http://yoursite.com/folder1/folder2/folder3',
where folder3 is final folder, contained all dcm files.

Also, you can read a lot of comments in tools/config.js : data description
