### ISSUE TITLE
Load specific files from url

### ISSUE THREAD

**Issue by Alaa-Nebli** [epam/mriviewer#85]
My problem is that I have too many files on the server and I'm looking to get only some specific files based on the user demand. 

When I was having only it was working bit now I think that he's loading all the data, so he can't handle them and he crashes. 
Any help please ? And thank you in advance

**Comment by DanilRostov** [comment]
@Alaa-Nebli  thank you for opening this issue,

We have bug with opening from direct link and we're going to fix it.
We will let you know as soon as it fixed.

**Comment by DanilRostov** [comment]
Dear @Alaa-Nebli, we fixed this bug in recent release. Please check it out. In case you face other problems please create separate issue. Thank you.
